#zmodload zsh/zprof # 与末尾的一起食用，性能分析
export GPG_TTY=$(tty)
export SAVEHIST=1000000 # 历史记录大小
#export HISTSIZE=100000 # 载入内存的大小
#setopt HIST_FIND_NO_DUPS # 搜索的时候完全一样的只出现一次
#setopt INC_APPEND_HISTORY # 立即记录历史文件而不是退出时
#export HISTTIMEFORMAT="[%F %T] " # 时间戳格式
#setopt EXTENDED_HISTORY # 记录时间戳
export ZSH="$HOME/.oh-my-zsh"
export LANG=zh_CN.UTF-8
#eval "$(/opt/homebrew/bin/brew shellenv)"

# 把代理提前移动上来，不然更新的时候有问题
# export https_proxy=http://127.0.0.1:6152
# export http_proxy=http://127.0.0.1:6152
# export all_proxy=socks5://127.0.0.1:6153

# ZSH theme
ZSH_THEME="powerlevel10k/powerlevel10k"
DISABLE_UPDATE_PROMPT=true # 自动更新不提示


# ZSH_THEME SETTINGS

#Powerlevel 10k.

#Powerlevel 10k elements.
#
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    os_icon
    virtualenv
    go_version
    context
    dir
    vcs
)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    command_execution_time
    status
    load
    ram
    background_jobs
    time
)
# Powerlevel 10k appearance.
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=30 # 自动补全 超过 30 忽略
ZSH_AUTOSUGGEST_USE_ASYNC=1 # 开启异步
VIRTUAL_ENV_DISABLE_PROMPT=1
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_TIME_FORMAT="%D{%Y-%m-%d %H:%M:%S}"
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_DIR_SHOW_WRITABLE=true
POWERLEVEL9K_HOST_ICON="\uF109 "
POWERLEVEL9K_SSH_ICON="\uF489 "

# VCS icons
POWERLEVEL9K_VCS_GIT_ICON=$'\uf1d3'
POWERLEVEL9K_VCS_GIT_GITHUB_ICON=$'\uf113'
POWERLEVEL9K_VCS_STAGED_ICON=$'\uf055'
POWERLEVEL9K_VCS_UNSTAGED_ICON=$'\uf071'
POWERLEVEL9K_VCS_UNTRACKED_ICON=$'\uf00d'
POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON=$'\uf0ab '
POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON=$'\uf0aa '

# VCS colours
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='black'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='red'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='black'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='yellow'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='black'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='green'

# VCS CONFIG
POWERLEVEL9K_SHOW_CHANGESET=false

bindkey "\033[1~" beginning-of-line
bindkey "\033[4~" end-of-line

# command alias
alias grep="grep --color=auto --exclude-dir=\.history"
alias ack="ack --ignore-directory=\.history"
# --------------- tidy below ------------
# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
# export ZSH="/home/xiekeyi/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
#ZSH_THEME="alanpeabody"

# Set list of themes to pick from when loading at random
# Setting this vagoriable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.  # ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
git
zsh-autosuggestions
)

source /etc/profile
source $ZSH/oh-my-zsh.sh
set -o vi # 使用 VIM 模式

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
#
# export tLC_ALL=en_US.UTF-8  
#

export PATH=$PATH:~/go/go/bin:~/dev/bin:~/dev/protobuf/bin
# export GO111MODULE=auto
export PATH="$PATH:/usr/local/opt/curl/bin:/home/keyixie/cmake/cmake-3.21.3-linux-x86_64/bin:$GOPATH/bin"


#export PYENV_HOME=/home/keyixie/.pyenv
#eval "$(pyenv init -)"


#export N_PREFIX=/usr/local #node实际安装位置
#export PATH=$N_PREFIX/bin:$PATH
#export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")" 
#[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" 
##source "$HOME/.zprofile"
#export NVM_DIR="$HOME/.nvm"
#[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
#[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
#source $HOME/.cargo/env

export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
eval $(thefuck --alias)
